YACLib: yaclib::detail::Injector Class Reference
yaclib::detail::Injector Class Reference
#include <injector.hpp>
Public Member Functions
Injector ()
void MaybeInject ()
Static Public Member Functions
static void SetFrequency (uint32_t freq)
static void SetSleepTime (uint32_t ns)
Detailed Description
Definition at line 9 of file injector.hpp.
Constructor & Destructor Documentation
Injector()
yaclib::detail::Injector::Injector () explicit
Definition at line 14 of file injector.cpp.
Member Function Documentation
MaybeInject()
void yaclib::detail::Injector::MaybeInject ()
Definition at line 17 of file injector.cpp.
Referenced by yaclib::InjectFault().
SetFrequency()
void yaclib::detail::Injector::SetFrequency (uint32_t freq) static
Definition at line 39 of file injector.cpp.
Referenced by yaclib::SetFaultFrequency().
SetSleepTime()
void yaclib::detail::Injector::SetSleepTime (uint32_t ns) static
Definition at line 43 of file injector.cpp.
Referenced by yaclib::SetFaultSleepTime().
The documentation for this class was generated from the following files:
include/yaclib/fault/injector.hpp
src/fault/injector.cpp