YACLib: yaclib::detail Namespace Reference
yaclib::detail Namespace Reference
Namespaces
namespace thread
Classes
class AllCombinator
class AllCombinatorBase
class AllCombinatorBase< void >
class AnyCombinator
class AnyCombinatorBase
class AnyCombinatorBase< V, E, WhenPolicy::FirstFail >
class AnyCombinatorBase< V, E, WhenPolicy::LastFail >
class Atomic
class Atomic< Impl, U * >
class AtomicBase
struct AtomicCounter
class AtomicEvent
class AtomicFlag
class AtomicFloatingBase
class AtomicFloatingBase< Impl, T, true >
class AtomicIntegralBase
class AtomicIntegralBase< Impl, T, true >
class AtomicWait
class AwaitAwaiter
class BaseCore
class BasePromiseType
class ConditionVariable
class ConditionVariableAny
class Core
struct DefaultDeleter
struct Destroy
class FuncWrapper
struct FutureBaseTypes
struct FutureBaseTypes< Future< V, E > >
struct FutureBaseTypes< FutureBase< V, E > >
struct FutureBaseTypes< FutureOn< V, E > >
struct Head
struct Head< T, Args... >
class Injector
class Inline
class InlineCore
struct InstantiationTypes
struct InstantiationTypes< Instance, Instance< V, E > >
struct Invoke
struct Invoke< Func, void >
struct IsInstantiationOf
struct IsInstantiationOf< Instance, Instance< Args... > >
struct IsInvocable
struct IsInvocable< Func, void >
class List
class Mutex
class MutexEvent
struct Node
Node class, used in intrusive data structure.
struct NopeCounter
struct NoTimeoutTag
class OnAwaiter
class PromiseType
class PromiseType< void, E >
struct PromiseTypeDeleter
class RecursiveMutex
class RecursiveTimedMutex
class ResultCore
class ResultCore< void, void >
struct Return
struct Return< V, E, Func, 1 >
struct Return< V, E, Func, 2 >
struct Return< V, E, Func, 4 >
struct Return< V, E, Func, 8 >
class SafeCall
struct SetAllDeleter
struct SetOneDeleter
class SharedFunc
class SharedMutex
class SharedTimedMutex
class TimedMutex
class UniqueJob
Typedefs
template<CoreType Type, typename V , typename E >
using ResultCoreT = std::conditional_t< Type==CoreType::Detach, ResultCore< void, void >, ResultCore< V, E > >
template<typename V , typename E >
using ResultCorePtr = IntrusivePtr< ResultCore< V, E > >
using DefaultEvent = MutexEvent
Enumerations
enum class CoreType : char { Run = 0 , Then = 1 , Detach = 2 }
enum class CallbackType : char { Inline = 0 , InlineOn = 1 , On = 2 }
enum class LogLevel : char { Debug = 0 , Info = 1 , Error = 2 , Count = 3 }
Functions
template<typename Event , typename Timeout , typename Range >
bool WaitRange (const Timeout &timeout, const Range &range, std::size_t count)
template<typename Event , typename Timeout , typename... Cores>
bool WaitCore (const Timeout &timeout, Cores &... cores)
template<typename Event , typename Timeout , typename Iterator >
bool WaitIterator (const Timeout &timeout, Iterator it, std::size_t count)
template bool WaitCore< DefaultEvent, NoTimeoutTag, BaseCore > (const NoTimeoutTag &, BaseCore &)
template<typename Combinator , typename It >
void WhenImpl (Combinator *combinator, It it, std::size_t count)
template<typename Combinator , typename E , typename... V>
void WhenImpl (Combinator *combinator, FutureBase< V, E > &&... futures)
template<typename V , typename E , typename Func >
constexpr char Tag () noexcept
template<CoreType Type, typename Arg , typename E , typename Func >
auto * MakeCore (Func &&f)
template<CoreType CoreT, CallbackType CallbackT, typename Arg , typename E , typename Func >
auto SetCallback (ResultCorePtr< Arg, E > caller, Func &&f)
template<typename Func >
Job * MakeUniqueJob (Func &&f)
void SetCallback (LogLevel level, LogCallback callback) noexcept
void LogMessage (LogLevel level, std::string_view file, std::size_t line, std::string_view func, std::string_view condition, std::string_view message)
Variables
static NopeCounter< Inline > sInline
constexpr int kFreq = 16
constexpr int kSleepTimeNs = 200
static std::array< LogCallback, static_cast< std::size_t >(LogLevel::Count)> sCallbacks = {}
Typedef Documentation
DefaultEvent
using yaclib::detail::DefaultEvent = typedef MutexEvent
Definition at line 16 of file default_event.hpp.
ResultCorePtr
template<typename V , typename E > using yaclib::detail::ResultCorePtr = typedef IntrusivePtr<ResultCore<V, E> >
Definition at line 77 of file result_core.hpp.
ResultCoreT
template<CoreType Type, typename V , typename E > using yaclib::detail::ResultCoreT = typedef std::conditional_t<Type == CoreType::Detach, ResultCore<void, void>, ResultCore<V, E> >
Definition at line 15 of file core.hpp.
Enumeration Type Documentation
CallbackType
enum class yaclib::detail::CallbackType : char strong
Enumerator
Inline
InlineOn
On
Definition at line 212 of file core.hpp.
CoreType
enum class yaclib::detail::CoreType : char strong
Enumerator
Run
Then
Detach
Definition at line 8 of file core.hpp.
LogLevel
enum class yaclib::detail::LogLevel : char strong
Enumerator
Debug
Info
Error
Count
Definition at line 14 of file log.hpp.
Function Documentation
LogMessage()
void yaclib::detail::LogMessage (LogLevel level, std::string_view file, std::size_t line, std::string_view func, std::string_view condition, std::string_view message)
Definition at line 10 of file log.cpp.
References sCallbacks.
MakeCore()
template<CoreType Type, typename Arg , typename E , typename Func > auto * yaclib::detail::MakeCore (Func && f)
Definition at line 198 of file core.hpp.
References Detach, and Run.
MakeUniqueJob()
template<typename Func > Job * yaclib::detail::MakeUniqueJob (Func && f)
Definition at line 33 of file unique_job.hpp.
Referenced by yaclib::Submit().
SetCallback() [1/2]
void yaclib::detail::SetCallback (LogLevel level, LogCallback callback) noexcept
Definition at line 17 of file log.cpp.
References sCallbacks.
SetCallback() [2/2]
template<CoreType CoreT, CallbackType CallbackT, typename Arg , typename E , typename Func > auto yaclib::detail::SetCallback (ResultCorePtr< Arg, E > caller, Func && f)
Definition at line 219 of file core.hpp.
References Inline, On, Run, and Then.
Tag()
template<typename V , typename E , typename Func > constexpr char yaclib::detail::Tag () constexpr noexcept
Definition at line 58 of file core.hpp.
WaitCore()
template<typename Event , typename Timeout , typename... Cores> bool yaclib::detail::WaitCore (const Timeout & timeout, Cores &... cores)
Definition at line 48 of file wait_impl.hpp.
WaitCore< DefaultEvent, NoTimeoutTag, BaseCore >()
template bool yaclib::detail::WaitCore< DefaultEvent, NoTimeoutTag, BaseCore > (const NoTimeoutTag & , BaseCore &)
WaitIterator()
template<typename Event , typename Timeout , typename Iterator > bool yaclib::detail::WaitIterator (const Timeout & timeout, Iterator it, std::size_t count)
Definition at line 58 of file wait_impl.hpp.
WaitRange()
template<typename Event , typename Timeout , typename Range > bool yaclib::detail::WaitRange (const Timeout & timeout, const Range & range, std::size_t count)
Definition at line 18 of file wait_impl.hpp.
References yaclib::detail::BaseCore::Empty(), yaclib::detail::BaseCore::ResetWait(), and yaclib::detail::BaseCore::SetWait().
WhenImpl() [1/2]
template<typename Combinator , typename E , typename... V> void yaclib::detail::WhenImpl (Combinator * combinator, FutureBase< V, E > &&... futures)
Definition at line 20 of file when_impl.hpp.
WhenImpl() [2/2]
template<typename Combinator , typename It > void yaclib::detail::WhenImpl (Combinator * combinator, It it, std::size_t count)
Definition at line 11 of file when_impl.hpp.
Referenced by yaclib::WhenAll(), and yaclib::WhenAny().
Variable Documentation
kFreq
constexpr int yaclib::detail::kFreq = 16 inline constexpr
Definition at line 7 of file injector.cpp.
kSleepTimeNs
constexpr int yaclib::detail::kSleepTimeNs = 200 inline constexpr
Definition at line 8 of file injector.cpp.
sCallbacks
std::array<LogCallback, static_cast<std::size_t>(LogLevel::Count)> yaclib::detail::sCallbacks = {} static
Definition at line 8 of file log.cpp.
Referenced by LogMessage(), and SetCallback().
sInline
NopeCounter<Inline> yaclib::detail::sInline static
Definition at line 20 of file inline.cpp.
Referenced by yaclib::MakeInline().