name: Coverage

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'doc/**', '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ 'doc/**', '**.md' ]

jobs:
  # TODO(MBkkt) Use gcc-11, now doesn't work in CI, only locally.

  main:
    runs-on: ubuntu-20.04

    env:
      YACLIB_FAULT: 'OFF ON'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pip ninja-build lld gcc-10 g++-10 lcov
          sudo ln -sf /usr/local/bin/ld /usr/bin/lld
          sudo pip install -U gcovr

      - name: Configure CMake
        run: |
          for yaclib_fault in ${YACLIB_FAULT[*]}; do
            dir="build_fault_${yaclib_fault}"
            echo $dir
          
            cmake -S . -B $dir                                                   \
              -G "Ninja"                                                         \
              -DCMAKE_BUILD_TYPE=Debug                                           \
              -DCMAKE_C_COMPILER=gcc-10                                          \
              -DCMAKE_CXX_COMPILER=g++-10                                        \
              -DYACLIB_FAULT=$yaclib_fault                                       \
              -DYACLIB_TEST=SINGLE                                               \
              -DYACLIB_FLAGS="COVERAGE;CORO"                                     \
              -DYACLIB_CXX_STANDARD=20     
          
          done

      - name: Build
        run: |
          for yaclib_fault in ${YACLIB_FAULT[*]}; do
            dir="build_fault_${yaclib_fault}"
            echo $dir
          
            ninja -C $dir
          done

      - name: Test
        run: |
          for yaclib_fault in ${YACLIB_FAULT[*]}; do
            dir="build_fault_${yaclib_fault}"
            echo $dir
          
            cd $dir
            ctest --output-on-failure -C Debug -V
            cd ..
          done

      - name: Collect lcov info
        run: |
          for yaclib_fault in ${YACLIB_FAULT[*]}; do
            dir="build_fault_${yaclib_fault}"
            echo $dir
          
            cd $dir
            lcov --rc lcov_branch_coverage=1 -d . -c                       -o lcov_cond.info
            lcov --rc lcov_branch_coverage=1 -r lcov_cond.info "/usr/*"    -o lcov_cond.info
            lcov --rc lcov_branch_coverage=1 -r lcov_cond.info "*/_deps/*" -o lcov_cond.info
            lcov --rc lcov_branch_coverage=1 -r lcov_cond.info "*/fault/*" -o lcov_cond.info
            lcov --rc lcov_branch_coverage=1 -r lcov_cond.info "*/test/*"  -o lcov_cond.info
            lcov                             -r lcov_cond.info             -o lcov.info
            lcov --rc lcov_branch_coverage=1 --list lcov_cond.info
            cd ..
          done
          
          lcov --add-tracefile build_fault_ON/lcov.info --add-tracefile build_fault_OFF/lcov.info --output-file ./total.info
          lcov --rc lcov_branch_coverage=1 --list ./total.info

      - name: codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./total.info
